[package]
name = "conda-server"
version = "0.1.0"
authors = ["Zhaosheng Pan <zhaosheng.pan@ximalaya.com>"]
edition = "2018"

[dependencies]
actix-files = "0.2"
actix-web = "2.0"
actix-rt = "1.0"
actix-multipart = "0.2"
env_logger = "0.7"
futures = "0.3"
